[package]
name = "rust-semp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
nalgebra = "0.30.1"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
psqs = { path = "/home/brent/Projects/psqs" }
symm = { path = "/home/brent/Projects/symm" }
taylor = { path = "/home/brent/Projects/taylor" }
rust-pbqff = { path = "/home/brent/Projects/rust-pbqff" }
rayon = "1.5.3"

[dev-dependencies]
approx = "0.5.1"

[[bin]]
name = "one_iter"

[[bin]]
name = "num_jac"

[[bin]]
name = "mopac"